import random
import os

ADJECTIVES = [
    'accueillant',
    'agressif',
    'adorable',
    'ambitieux',
    'alourdi',
    'attrayant',
    'beau',
    'carré',
    'chaleureux',
    'confiant',
    'combatif',
    'combative',
    'costaud',
    'coopératif',
    'crasseux',
    'cruel',
    'désillusionné',
    'dangereux',
    'droit',
    'dynamique',
    'élégant',
    'énervé',
    'gai',
    'gentil',
    'grand',
    'gros',
    'hideux',
    'hirsute',
    'franc',
    'inquiet',
    'généreux',
    'magnifique',
    'harmonieux',
    'maigre',
    'hésitant',
    'maladroit',
    'merveilleux',
    'impartial',
    'mince',
    'nerveux',
    'instinctif',
    'offensé',
    'intrépide',
    'parfait',
    'jaloux',
    'plaisant',
    'lâche',
    'propre',
    'vivace',
    'mauvais',
    'poule',
    'ravissant',
    'mystérieux',
    'réfléchi',
    'sale',
    'plaisant',
    'sauvage',
    'ponctuel',
    'séduisant',
    'sombre',
    'protecteur',
    'souriant',
    'succecieux',
    'splendide',
    'svelte',
    'tendu',
    'terne',
    'timide',
    'trompeur',
    'vif',
    'spirituel',
    'talentueux',
    'altéré',
    'colossal',
    'carré',
    'considérable',
    'circulaire',
    'énorme',
    'creux',
    'altéré',
    'décomposé',
    'fin',
    'déformé',
    'gigantesque',
    'droit',
    'grand',
    'étroit',
    'immense',
    'géométrique',
    'important',
    'large',
    'imposant',
    'long\xa0longue',
    'infime',
    'maigre',
    'large',
    'plat',
    'menu',
    'primitif',
    'minuscule',
    'raide',
    'monumental',
    'rectangulaire',
    'rond',
    'petit',
    'simple',
    'spacieux',
    'tordu',
    'super',
    'vaste',
    'amoureux',
    'actuel',
    'anxieux',
    'ancien',
    'beau',
    'belle',
    'annuel',
    'bourru',
    'antique',
    'calme',
    'avancé',
    'choqué',
    'bref',
    'coquin',
    'contemporain',
    'coupable',
    'débordé',
    'hebdomadaire',
    'dégoûté',
    'jeune',
    'déprimé',
    'journalier',
    'dérangé',
    'lent',
    'douloureux',
    'mensuel',
    'effrayé',
    'moderne',
    'colerique',
    'neuf',
    'ennuyé',
    'nouveau',
    'envieux',
    'précipité',
    'épuisé',
    'prompt',
    'exaspéré',
    'rapide',
    'extatique',
    'fâché',
    'fatigué',
    'faux',
    'fidèle',
    'fier',
    'fourbe',
    'frustré',
    'gêné',
    'gentil',
    'heureux',
    'honteux',
    'horrible',
    'hystérique',
    'indisposé',
    'jovial',
    'malade',
    'malicieux',
    'mature',
    'mauvais',
    'méchant',
    'pacifique',
    'peiné',
    'perplexe',
    'perturbé',
    'prétentieux',
    'prudent',
    'rieur',
    'solitaire',
    'soucieux',
    'souffrant',
    'soupçonneux',
    'timide',
    'tranquille',
    'triste',
    'troublé'
]
ANIMALS = [
    'Abeille', 'Agneau', 'Aigle', 'Albatros', 'Asticot', 'Alligator',
    'Alpaga', 'Ane', 'Anguille', 'Antilope', 'Araignée', 'Asticot',
    'Autruche', 'Babouin', 'Baleine', 'Béluga', 'Bigorneau', 'Bison',
    'Blaireau', 'Blobfish', 'Boa', 'Boeuf', 'Bourdon', 'Buffle',
    'Cafard', 'Calmar', 'Caméléon', 'Canard', 'Caribou', 'Carpe',
    'Castor', 'Cerf', 'Chacal', 'Chameau', 'Chamois', 'Chat',
    'Chauve-souris', 'Chenille', 'Cheval', 'Chèvre', 'Chevreuil',
    'Chien', 'Chimpanzé', 'Chouette', 'Cigale', 'Cigogne', 'Cobra',
    'Coccinelle', 'Cochon', 'Colombe', 'Coq', 'Couleuvre', 'Coyote',
    'Crabe', 'Crapaud', 'Crevette', 'Criquet', 'Crocodile', 'Cygne',
    'Dauphin', 'Dromadaire', 'Ecureuil', 'Eléphant', 'Escargot',
    'Espadon', 'Fennec', 'Flament rose', 'Fouine', 'Fourmi', 'Frelon',
    'Furet', 'Gendarme', 'Gerbille', 'Girafe', 'Gorille', 'Grenouille',
    'Guépard', 'Guêpe', 'Hamster', 'Hérisson', 'Hibou', 'Hippocampe',
    'Hippopotame', 'Hirondelle', 'Homard', 'Huître', 'Hyène', 'Iguane',
    'Jaguar', 'Kangourou', 'Kiwi', 'Koala', 'Lama', 'Lapin', 'Larve',
    'Léopard', 'Lézard', 'Libellule', 'Lièvre', 'Limace', 'Lion', 'Loup',
    'Loutre', 'Luciole', 'Lynx', 'Macaque', 'Manchot', 'Mante religieuse',
    'Méduse', 'Mille-pattes', 'Morse', 'Mouche', 'Moustique', 'Mouton',
    'Mulet', 'Mygale', 'Narval', 'Oie', 'Orang-outan', 'Ornithorynque', 'Orque',
    'Otarie', 'Ouistiti', 'Ours', 'Panda', 'Panda roux', 'Pangolin', 'Panthère',
    'Paon', 'Papillon', 'Paresseux', 'Pélican', 'Perce-oreille', 'Perroquet',
    'Perruche', 'Phacochère', 'Phasme', 'Phoque', 'Pieuvre', 'Pigeon', 'Piranha',
    'Poisson rouge', 'Poisson', 'Poisson-globe', 'Poney', 'Porc', 'Porc-épic',
    'Pou', 'Poule', 'Poulpe', 'Poussin', 'Puce', 'Puma', 'Punaise', 'Putois',
    'Python', 'Raie', 'Rat', 'Renard', 'Requin', 'Requin-marteau', 'Rhinocéros',
    'Rouge-gorge', 'Salamandre', 'Sanglier', 'Sangsue', 'Sardine', 'Saumon', 'tarantule', "table", "maison"
    'Scarabée', 'Scorpion', 'Serpent', 'Singe', 'Souris', 'Suricate', 'Tapir',
    'Tatou', 'Taupe', 'Taureau', 'Thon', 'Tigre', 'Tortue', 'Toucan', 'Triton',
    'Truite', 'Vache', 'Vautour', 'Ver', 'Ver de terre', 'Vipère', 'Zèbre', "Pika", "bibitte_pattate"
]

def fancy_name(folder_path: str):
    animal = random.sample(ANIMALS, 1)[0].lower()
    adjective = random.sample(ADJECTIVES, 1)[0]
    full_name = "_".join([animal, adjective])
    folders = os.listdir(folder_path)
    if full_name in folders:
        return fancy_name(folder_path)
    return full_name

if __name__ == "__main__":
    print(fancy_name("./"))