import random
import os

ADJECTIVES = [
    'accueillant',
    'agressif',
    'adorable',
    'ambitieux',
    'alourdi',
    'attrayant',
    'beau',
    'carre',
    'chaleureux',
    'confiant',
    'combatif',
    'combative',
    'costaud',
    'cooperatif',
    'crasseux',
    'cruel',
    'desillusionne',
    'dangereux',
    'droit',
    'dynamique',
    'elegant',
    'enerve',
    'gai',
    'gentil',
    'grand',
    'gros',
    'hideux',
    'hirsute',
    'franc',
    'inquiet',
    'genereux',
    'magnifique',
    'harmonieux',
    'maigre',
    'hesitant',
    'maladroit',
    'merveilleux',
    'impartial',
    'mince',
    'nerveux',
    'instinctif',
    'offense',
    'intrepide',
    'parfait',
    'jaloux',
    'plaisant',
    'lâche',
    'propre',
    'vivace',
    'mauvais',
    'poule',
    'ravissant',
    'mysterieux',
    'reflechi',
    'sale',
    'plaisant',
    'sauvage',
    'ponctuel',
    'seduisant',
    'sombre',
    'protecteur',
    'souriant',
    'succecieux',
    'splendide',
    'svelte',
    'tendu',
    'terne',
    'timide',
    'trompeur',
    'vif',
    'spirituel',
    'talentueux',
    'altere',
    'colossal',
    'carre',
    'considerable',
    'circulaire',
    'enorme',
    'creux',
    'altere',
    'decompose',
    'fin',
    'deforme',
    'gigantesque',
    'droit',
    'grand',
    'etroit',
    'immense',
    'geometrique',
    'important',
    'large',
    'imposant',
    'long\xa0longue',
    'infime',
    'maigre',
    'large',
    'plat',
    'menu',
    'primitif',
    'minuscule',
    'raide',
    'monumental',
    'rectangulaire',
    'rond',
    'petit',
    'simple',
    'spacieux',
    'tordu',
    'super',
    'vaste',
    'amoureux',
    'actuel',
    'anxieux',
    'ancien',
    'beau',
    'belle',
    'annuel',
    'bourru',
    'antique',
    'calme',
    'avance',
    'choque',
    'bref',
    'coquin',
    'contemporain',
    'coupable',
    'deborde',
    'hebdomadaire',
    'degoûte',
    'jeune',
    'deprime',
    'journalier',
    'derange',
    'lent',
    'douloureux',
    'mensuel',
    'effraye',
    'moderne',
    'colerique',
    'neuf',
    'ennuye',
    'nouveau',
    'envieux',
    'precipite',
    'epuise',
    'prompt',
    'exaspere',
    'rapide',
    'extatique',
    'fâche',
    'fatigue',
    'faux',
    'fidele',
    'fier',
    'fourbe',
    'frustre',
    'gêne',
    'gentil',
    'heureux',
    'honteux',
    'horrible',
    'hysterique',
    'indispose',
    'jovial',
    'malade',
    'malicieux',
    'mature',
    'mauvais',
    'mechant',
    'pacifique',
    'peine',
    'perplexe',
    'perturbe',
    'pretentieux',
    'prudent',
    'rieur',
    'solitaire',
    'soucieux',
    'souffrant',
    'soupçonneux',
    'timide',
    'tranquille',
    'triste',
    'trouble'
]
ANIMALS = [
    'Abeille', 'Agneau', 'Aigle', 'Albatros', 'Asticot', 'Alligator',
    'Alpaga', 'Ane', 'Anguille', 'Antilope', 'Araignee', 'Asticot',
    'Autruche', 'Babouin', 'Baleine', 'Beluga', 'Bigorneau', 'Bison',
    'Blaireau', 'Blobfish', 'Boa', 'Boeuf', 'Bourdon', 'Buffle',
    'Cafard', 'Calmar', 'Cameleon', 'Canard', 'Caribou', 'Carpe',
    'Castor', 'Cerf', 'Chacal', 'Chameau', 'Chamois', 'Chat',
    'Chauve-souris', 'Chenille', 'Cheval', 'Chevre', 'Chevreuil',
    'Chien', 'Chimpanze', 'Chouette', 'Cigale', 'Cigogne', 'Cobra',
    'Coccinelle', 'Cochon', 'Colombe', 'Coq', 'Couleuvre', 'Coyote',
    'Crabe', 'Crapaud', 'Crevette', 'Criquet', 'Crocodile', 'Cygne',
    'Dauphin', 'Dromadaire', 'Ecureuil', 'Elephant', 'Escargot',
    'Espadon', 'Fennec', 'Flament rose', 'Fouine', 'Fourmi', 'Frelon',
    'Furet', 'Gendarme', 'Gerbille', 'Girafe', 'Gorille', 'Grenouille',
    'Guepard', 'Guepe', 'Hamster', 'Herisson', 'Hibou', 'Hippocampe',
    'Hippopotame', 'Hirondelle', 'Homard', 'Huître', 'Hyene', 'Iguane',
    'Jaguar', 'Kangourou', 'Kiwi', 'Koala', 'Lama', 'Lapin', 'Larve',
    'Leopard', 'Lezard', 'Libellule', 'Lievre', 'Limace', 'Lion', 'Loup',
    'Loutre', 'Luciole', 'Lynx', 'Macaque', 'Manchot', 'Mante religieuse',
    'Meduse', 'Mille-pattes', 'Morse', 'Mouche', 'Moustique', 'Mouton',
    'Mulet', 'Mygale', 'Narval', 'Oie', 'Orang-outan', 'Ornithorynque', 'Orque',
    'Otarie', 'Ouistiti', 'Ours', 'Panda', 'Panda roux', 'Pangolin', 'Panthere',
    'Paon', 'Papillon', 'Paresseux', 'Pelican', 'Perce-oreille', 'Perroquet',
    'Perruche', 'Phacochere', 'Phasme', 'Phoque', 'Pieuvre', 'Pigeon', 'Piranha',
    'Poisson rouge', 'Poisson', 'Poisson-globe', 'Poney', 'Porc', 'Porc-epic',
    'Pou', 'Poule', 'Poulpe', 'Poussin', 'Puce', 'Puma', 'Punaise', 'Putois',
    'Python', 'Raie', 'Rat', 'Renard', 'Requin', 'Requin-marteau', 'Rhinoceros',
    'Rouge-gorge', 'Salamandre', 'Sanglier', 'Sangsue', 'Sardine', 'Saumon', 'tarantule', "table", "maison"
    'Scarabee', 'Scorpion', 'Serpent', 'Singe', 'Souris', 'Suricate', 'Tapir',
    'Tatou', 'Taupe', 'Taureau', 'Thon', 'Tigre', 'Tortue', 'Toucan', 'Triton',
    'Truite', 'Vache', 'Vautour', 'Ver', 'Ver de terre', 'Vipere', 'Zebre', "Pika", "bibitte_pattate"
]

def fancy_name(folder_path: str):
    animal = random.sample(ANIMALS, 1)[0].lower()
    adjective = random.sample(ADJECTIVES, 1)[0]
    full_name = "_".join([animal, adjective])
    try:
        folders = os.listdir(folder_path)
    except:
        folders = []
    if full_name in folders:
        return fancy_name(folder_path)
    return full_name

if __name__ == "__main__":
    print(fancy_name("./"))
